### ISSUE TITLE
tons of problems

### ISSUE THREAD

**Issue by CodeDotJS** [cauealves/pagespeed-score-cli#3]
hi @cauealves 

`pagespeed-score-cli` is a nice tool but it has lots of issues and lots of unusable stuffs.
- unused `var` : because of meow
- unused `modules` : because of meow
- useless `spaces` : dependencies
- problem while supplying arguments

`If no argument supplied, the tool will run but without showing any output`

`IFprotocol isn't supplied, the tool will run but it won't show the result`
- valid url problem : no function to check whether the supplied url is valid or not
- connection problem - tools keeps running even if there is no connection

**Comment by caueops** [comment]
Thanks for contribution.
