### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by tarungarg546** [cauealves/pagespeed-score-cli#9]
Hey,

What about having a contributing guide. So that before sending PR they have everything tested and ready.

I can submit a PR if you want it.

**Comment by CodeDotJS** [comment]
No need of adding any contributing guide. 

Most of the people are already familiar with the contributing process, moreover if someone sends any pull request, it' will be automatically tested via .travis.yml which will inform the developer whether code has any further issues or not :)

**Comment by caueops** [comment]
I believe that there may be people who are starting and often do not know how to contribute to an open-source project. I myself am beginning and always try some documentation repositories before contributing.

It may be good :)

**Comment by CodeDotJS** [comment]
@cauealves :+1:

**Comment by tarungarg546** [comment]
#10
